# Generated by Django 5.2 on 2025-04-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='desscription',
            new_name='description',
        ),
    ]
